positions:
  # Generic Safe Positions
  robot_home: [180.0, -45.0, 0.0, 45.0, 90.0]
  robot_home_back: [0.0, -45.0, 0.0, 45.0, 90.0]
  robot_home_left: [90.0, -45.0, 0.0, 45.0, 90.0]
  robot_home_right: [270.0, -45.0, 0.0, 45.0, 90.0]
  
  # The following happens when linear rail is at 0, no payload allowed
  uplc_draw_home: [176.5, 8.1, -70.1, 62.1, 90.0]
  uplc_draw_open_max: [174.5, 8.3, -70.4, 62.2, 88] # slight further from fully open
  uplc_draw_open_min: [144.3, 30.8, -103, 72, 57.8] # slight short from fully close
  uplc_draw_open_close: [143.4, 32.7, -106.0, 73.1, 56.9] # You hear a "click"
  
  #uplc_plate_home: [90.8, -33.62, -52.86, 84.78, 272.04]
  #uplc_plate_high: [136.8, -4.5, -78, 81, 318]
  #uplc_plate_drop: []
  #uplc_plate_low: [136.8, -3.3, -62.5, 64.3, 317.9]

  #ot2_home: [90.0, -45.0, 0.0, 45.0, 90.0]
  #ot2_high: []


  # The following happens when linear rail is at Deck location (550mm)
  # The Arm can reach the solid handler, the deck plates, and the fumehood positions
  deck_home: [90.0, -45.0, 0.0, 45, -90.0]
  deck_high: [165.58, -88.51, 4.76, 82.96, -14.22]
  deck_slot1_high: [202.51, -2.59, -19.97, 21.97, 22.28]
  deck_slot1_low: [202.54, 33.18, -27.42, -6.34, 21.78]
  deck_slot1_high_y_dir: [211.41, 25.12, -60.52, 35.76, 121.38]
  deck_slot1_low_y_dir: [211.40, 46.38, -65.99, 19.97, 121.08]
  deck_slot2_high: [215.68, -37.97, 1.16, 36.20, 35.63]
  deck_slot2_low: [215.75, 34.68, -10.00, -25.30, 34.66]
  decks_slot2_high_y_dir: [220.66, 9.40, -37.66, 28.64, 130.54]
  deck_slot2_low_y_dir: [220.65, 38.24, -43.98, 6.12, 130.11]
  deck_solid_high: [141.51, -31.05, -16.86, 46.73, -38.38]
  deck_solid_low: [141.50, -6.09, -12.36, 17.27, -38.80]

  # The following happens when linear rail is at Hood location (same as Deck for now  )
  # The Arm can reach the shaker and filteration setup in the fumehoods
  hood_home: []
  hood_shaker_high: []
  hood_shaker_low: []
  # hood_shaker_drop: []
  hood_filteration_high: []
  # hood_filteration_drop: []
  hood_filteration_low: []

  # The following happens when linear rail is at Cytation location
  cytation_home: []
  cytation_high: []
  cytation_low: []
  #
  plateloc_home: []
  plateloc_high: []
  plateloc_low: []
