positions:
  # Generic Safe Positions
  robot_home: [180.0, -45.0, 0.0, 45.0, 90.0]
  robot_home_back: [0.0, -45.0, 0.0, 45.0, 90.0]
  robot_home_left: [90.0, -45.0, 0.0, 45.0, 90.0]
  robot_home_right: [270.0, -45.0, 0.0, 45.0, 90.0]
  
  # The following happens when linear rail is at 0, no payload allowed
  uplc_home: [90.0, -45.0, 0.0, 45.0, 90.0]
  uplc_draw_home: [176.5, 8.1, -70.1, 62.1, 90.0]
  uplc_draw_open_max: [174.5, 8.3, -70.4, 62.2, 88] # slight further from fully open
  uplc_draw_open_min: [144.3, 30.8, -103, 72, 57.8] # slight short from fully close
  uplc_draw_open_close: [143.4, 32.7, -106.0, 73.1, 56.9] # You hear a "click"
  
  uplc_plate_home: [90.05, -54.66, -40.29, 94.98, -89.63]
  uplc_plate_high: [137.34, -3.34, -77.49, 80.08, -40.48]
  uplc_plate_in: [137.3, -2.11, -63.97, 65.32, -40.59]

  # The following happens when linear rail is at Deck location (550mm)
  # The Arm can reach the solid handler, the deck plates, and the fumehood positions
  deck_home: [90.0, -45.0, 0.0, 45, -90.0] # gripper
  deck_high: [180, -45, 0, 45, 0]
  deck_slot1_high: [202.88, 6.43, -20.05, 13.03, 22.50]             
  deck_slot1_low: [203.08, 33.13, -27.07, -6.66, 22.31]             # Gripper close to 120mm to grip from long side
  deck_slot1_low_press: [203.08, 33.63, -27.28, -6.95, 22.31]       # Press plate down
  deck_slot2_high: [215.76, -31.78, 0.96, 31.04, 35.6]
  deck_slot2_low: [215.82, 28.62, -8.26, -20.15, 34.78]

  # TODO: adjust these positions to be more accurate
  # deck_slot1_high_y_dir: [211.41, 25.12, -60.52, 35.76, 121.38] # gripper has to be at 90
  # deck_slot1_low_y_dir: [211.40, 46.38, -65.99, 19.97, 121.08] # gripper has to be at 90
  # deck_slot2_high: [215.68, -37.97, 1.16, 36.20, 35.63]
  # deck_slot2_low: [215.75, 34.68, -10.00, -25.30, 34.66]
  # decks_slot2_high_y_dir: [220.66, 9.40, -37.66, 28.64, 130.54] # gripper has to be at 90
  # deck_slot2_low_y_dir: [220.65, 38.24, -43.98, 6.12, 130.11] # gripper has to be at 90
  
  deck_solid_high:  [141.51, -31.05, -16.86, 46.73, -38.38]
  deck_solid_low: [142.08, -6.86, -11.19, 16.88, -38.23]
  deck_solid_low_press: [142.08, -6.26, -11.22, 16.3, -38.24]

  # The following happens when linear rail is at Hood location (same as Deck for now  )
  # The Arm can reach the shaker and filteration setup in the fumehoods
  hood_home: [-4.42, -67.82, 8.18, 59.11, -4.33]
  hood_shaker_high: [5.13, 28.61, -61.45, 32.40, 4.98]
  hood_shaker_low: [4.92, 39.45, -63.74, 23.85, 4.62]              # Gripper close to 120mm to grip from long side
  hood_shaker_low_press: [5.14, 39.80, -63.90, 23.68, 4.84]         # Press plate down

  hood_filter_home: [-46.10, -5.22, -32.69, 37.49, -46.08]      
  hood_filter_high: [-28.3, 29.88, -81.07, 50.85, -28.15]     
  hood_filter_low: [-28.39, 35.58, -79.92, 44, -28.33]           # Gripper close to 120mm to grip from long side  and away from filteration plate
  # hood_filter_low_press: [-28.19, 36.01, -80.23, 43.82, -28.06]     # Press plate down
  hood_filter_top_plate: [-28.19, 32.05, -80.86, 48.42, -27.99]     # Position to grip top plate of filteration plate

  # The following happens when linear rail is at Home
  opentrons_home: [-4.42, -67.82, 8.18, 59.11, -4.33]
  opentrons_2_high: [-2.28, 7.22, -25.61, 17.89, -2.62]
  opentrons_2_low: [-2.21, 33.11, -31.79, -1.83, -2.93]             # Gripper close to 120mm to grip from long side
  opentrons_2_low_press: [-2.20, 33.82, -32.07, -2.26, -2.94]       # Press plate down
  opentrons_4_high: [15.02, 22.82, -48.26, 25.01, 14.78]
  opentrons_4_low: [15.05, 35.6, -51.31, 15.28, 14.63]
  opentrons_6_high: [-18.22, 33.43, -52.03, 17.92, -18.60]
  opentrons_6_low: [-18.20, 41.26, -54.90, 12.96, -18.69]
  opentrons_6_low_press: [-18.20, 41.63, -55.06, 12.75, -18.69]

  # The following happens when linear rail is at Cytation location
  # cytation_home: []
  # cytation_high: []
  # cytation_low: []

  # plateloc_home: []
  # plateloc_high: []
  # plateloc_low: []
